### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/celeba256_250000.pt'

### ISSUE THREAD

**Issue by fittiing** [andreas128/RePaint#39]
Hi, hello, why do I execute it python test.py --conf_path confs/face_example.yml，The final result is this.
root@autodl-container-085311853c-58f07e12:~/RePaint-main# python test.py --conf_path confs/face_example.yml
Start face_example
Traceback (most recent call last):
  File "test.py", line 180, in <module>
    main(conf_arg)
  File "test.py", line 70, in main
    dist_util.load_state_dict(os.path.expanduser(
  File "/root/RePaint-main/guided_diffusion/dist_util.py", line 39, in load_state_dict
    with bf.BlobFile(path, "rb") as f:
  File "/root/miniconda3/lib/python3.8/site-packages/blobfile/_ops.py", line 356, in BlobFile
    return default_context.BlobFile(
  File "/root/miniconda3/lib/python3.8/site-packages/blobfile/_context.py", line 883, in BlobFile
    f = io.FileIO(path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/celeba256_250000.pt'

I'm looking forward to your answer. Thank you

**Comment by Hydrageno** [comment]
> Hi, hello, why do I execute it python test.py --conf_path confs/face_example.yml，The final result is this. root@autodl-container-085311853c-58f07e12:~/RePaint-main# python test.py --conf_path confs/face_example.yml Start face_example Traceback (most recent call last): File "test.py", line 180, in main(conf_arg) File "test.py", line 70, in main dist_util.load_state_dict(os.path.expanduser( File "/root/RePaint-main/guided_diffusion/dist_util.py", line 39, in load_state_dict with bf.BlobFile(path, "rb") as f: File "/root/miniconda3/lib/python3.8/site-packages/blobfile/_ops.py", line 356, in BlobFile return default_context.BlobFile( File "/root/miniconda3/lib/python3.8/site-packages/blobfile/_context.py", line 883, in BlobFile f = io.FileIO(path, mode=mode) FileNotFoundError: [Errno 2] No such file or directory: './data/pretrained/celeba256_250000.pt'
> 
> I'm looking forward to your answer. Thank you

Hi, you need to download the pretrained model: https://drive.google.com/uc?id=1norNWWGYP3EZ_o05DmoW1ryKuKMmhlCX
Download all pretrained models by executing download.sh
