### ISSUE TITLE
Has anyone else had this problem?

### ISSUE THREAD

**Issue by Supzekun** [andreas128/RePaint#47]
when python test.py --conf_path confs/face_example.yml
got error

Traceback (most recent call last):
  File "test.py", line 29, in <module>
    from guided_diffusion import dist_util
  File "/data/123/szk/RePaint-main/RePaint-main/guided_diffusion/dist_util.py", line 23, in <module>
    import blobfile as bf
  File "/home/123/.local/lib/python3.8/site-packages/blobfile/__init__.py", line 6, in <module>
    from blobfile._ops import (
  File "/home/123/.local/lib/python3.8/site-packages/blobfile/_ops.py", line 19, in <module>
    from blobfile._common import DirEntry, Stat, RemoteOrLocalPath
  File "/home/123/.local/lib/python3.8/site-packages/blobfile/_common.py", line 1025, in <module>
    RemoteOrLocalPath = Union[str, BlobPathLike, os.PathLike[str]]
TypeError: 'ABCMeta' object is not subscriptable

**Comment by mushen12138** [comment]
我也遇到了，有什么解决方法吗？

**Comment by lszyy001** [comment]
change the
    RemoteOrLocalPath = Union[str, BlobPathLike, os.PathLike[str]]
to
    RemoteOrLocalPath = Union[str, BlobPathLike, "os.PathLike[str]"]
then it works.

**Comment by jbnjvc10000** [comment]
It looks like the error is related to "blobfile"
This may be because linux has a different file structure（or file path?）
https://pypi.org/project/blobfile/
