### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by XiruiTeng** [andreas128/RePaint#52]
Traceback (most recent call last):
  File "test.py", line 179, in <module>
    conf_arg.update(yamlread(args.get('conf_path')))
  File "/root/test/RePaint/utils/__init__.py", line 29, in yamlread
    return yaml.safe_load(txtread(path=path))
  File "/root/test/RePaint/utils/__init__.py", line 23, in txtread
    path = os.path.expanduser(path)
  File "/root/anaconda3/envs/try/lib/python3.7/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType？
I meet this error can anyone help me ?

**Comment by Yuccccchan** [comment]
Do you find the solution? I meet this error too

**Comment by Jasontxr** [comment]
> Do you find the solution? I meet this error too
I ran the project again and the bug disappeared. Amazing.

**Comment by XiruiTeng** [comment]
> Do you find the solution? I meet this error too

I ran the project again and this error disappeared. Amazing.

**Comment by Lxq-0417** [comment]
I meet this error too
