### ISSUE TITLE
IndexError | Linux | face_example

### ISSUE THREAD

**Issue by justuser-31** [andreas128/RePaint#9]
Hello,
When i finished "setup"(instruction in README.md), i get this error:
<sub> [void@linux RePaint]$ prime-run python3 test.py --conf_path confs/face_example.yml
Start face_example
Traceback (most recent call last):
  File "/home/void/Downloads/RePaint/test.py", line 180, in <module>
    main(conf_arg)
  File "/home/void/Downloads/RePaint/test.py", line 66, in main
    model, diffusion = create_model_and_diffusion(
  File "/home/void/Downloads/RePaint/guided_diffusion/script_util.py", line 135, in create_model_and_diffusion
    diffusion = create_gaussian_diffusion(
  File "/home/void/Downloads/RePaint/guided_diffusion/script_util.py", line 288, in create_gaussian_diffusion
    return SpacedDiffusion(
  File "/home/void/Downloads/RePaint/guided_diffusion/respace.py", line 119, in __init__
    super().__init__(conf=conf, **kwargs)
  File "/home/void/Downloads/RePaint/guided_diffusion/gaussian_diffusion.py", line 158, in __init__
    np.append(self.posterior_variance[1], self.posterior_variance[1:])
IndexError: index 1 is out of bounds for axis 0 with size 1</sub>

My config file "face_example.yml" as default config exclude `diffusion_steps: 200` (because my system kill the process with `diffusion_steps: 1000` - I have only 8GB RAM)

I hope for your quick help
Sincerely, Justuser.

# ----------------SOLUTION-------------------:
## > Also others parameters maybe cause error.

**Comment by andreas128** [comment]
We describe how to modify the number of steps in the section "How to speed up the inference?" in the README.md.

Does that help? What is the error you get with `diffusion_steps: 1000`?

**Comment by justuser-31** [comment]
Hmm...With your parameter it works!!!  
>(When all applications closed)

Thank you,but i don't understand what do this parameters:
<sub>  n_sample: 1
  jump_length: 1
  jump_n_sample: 1</sub>
When changing parameters it doesn't run faster or slower.
**For what this?**

Also i noticed that this program uses only 1 "Thread" of CPU.
**Can i use more threads? And will it faster?**
